services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=entitlements'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
#      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh

  redis:
    image: 'redis:latest'
    ports:
      - '6379'