spring:
  application:
    name: entitlements-demo

  threads:
    virtual:
      enabled: true

  graphql:
    graphiql:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

