spring:
  application:
    name: entitlements-demo
  graphql:
    graphiql:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.postgres9.Dialect
